### ISSUE TITLE
Electron for simple to use

### ISSUE THREAD

**Issue by dutchakdev** [sonm-io/Wallet#22]
For simple to use our wallet, it think good idea to use electron wrapper.

**Comment by dmitrypisanko** [comment]
We allready working on electron version. It will be published in next wallet major release.

**Comment by mr-tron** [comment]
And it`s disappeared again. 

![image](https://user-images.githubusercontent.com/702560/40878689-70758738-668c-11e8-93b2-fb3d038904ed.png)

**Comment by dmitrypisanko** [comment]
We will release electron version on next week
